//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeleniumDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeleniumDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 中文.
        /// </summary>
        internal static string HomeLanguageChinese {
            get {
                return ResourceManager.GetString("HomeLanguageChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string HomeLanguageEnglish {
            get {
                return ResourceManager.GetString("HomeLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        internal static string HomeLanguageFrench {
            get {
                return ResourceManager.GetString("HomeLanguageFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deutsch.
        /// </summary>
        internal static string HomeLanguageGerman {
            get {
                return ResourceManager.GetString("HomeLanguageGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italiano.
        /// </summary>
        internal static string HomeLanguageItalian {
            get {
                return ResourceManager.GetString("HomeLanguageItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日本語.
        /// </summary>
        internal static string HomeLanguageJapanese {
            get {
                return ResourceManager.GetString("HomeLanguageJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polski.
        /// </summary>
        internal static string HomeLanguagePolish {
            get {
                return ResourceManager.GetString("HomeLanguagePolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        internal static string HomeLanguagePortuguese {
            get {
                return ResourceManager.GetString("HomeLanguagePortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        internal static string HomeLanguageRussian {
            get {
                return ResourceManager.GetString("HomeLanguageRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Español.
        /// </summary>
        internal static string HomeLanguageSpanish {
            get {
                return ResourceManager.GetString("HomeLanguageSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://zh.wikipedia.org.
        /// </summary>
        internal static string HomeURLChinese {
            get {
                return ResourceManager.GetString("HomeURLChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://en.wikipedia.org.
        /// </summary>
        internal static string HomeURLEnglish {
            get {
                return ResourceManager.GetString("HomeURLEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://fr.wikipedia.org.
        /// </summary>
        internal static string HomeURLFrench {
            get {
                return ResourceManager.GetString("HomeURLFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://de.wikipedia.org.
        /// </summary>
        internal static string HomeURLGerman {
            get {
                return ResourceManager.GetString("HomeURLGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://it.wikipedia.org.
        /// </summary>
        internal static string HomeURLItalian {
            get {
                return ResourceManager.GetString("HomeURLItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ja.wikipedia.org.
        /// </summary>
        internal static string HomeURLJapanese {
            get {
                return ResourceManager.GetString("HomeURLJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pl.wikipedia.org.
        /// </summary>
        internal static string HomeURLPolish {
            get {
                return ResourceManager.GetString("HomeURLPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://pt.wikipedia.org.
        /// </summary>
        internal static string HomeURLPortuguese {
            get {
                return ResourceManager.GetString("HomeURLPortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ru.wikipedia.org.
        /// </summary>
        internal static string HomeURLRussian {
            get {
                return ResourceManager.GetString("HomeURLRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://es.wikipedia.org.
        /// </summary>
        internal static string HomeURLSpanish {
            get {
                return ResourceManager.GetString("HomeURLSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;zh&apos;]/a.
        /// </summary>
        internal static string HomeXPathChinese {
            get {
                return ResourceManager.GetString("HomeXPathChinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;en&apos;]/a.
        /// </summary>
        internal static string HomeXPathEnglish {
            get {
                return ResourceManager.GetString("HomeXPathEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;fr&apos;]/a.
        /// </summary>
        internal static string HomeXPathFrench {
            get {
                return ResourceManager.GetString("HomeXPathFrench", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;de&apos;]/a.
        /// </summary>
        internal static string HomeXPathGerman {
            get {
                return ResourceManager.GetString("HomeXPathGerman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;it&apos;]/a.
        /// </summary>
        internal static string HomeXPathItalian {
            get {
                return ResourceManager.GetString("HomeXPathItalian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;ja&apos;]/a.
        /// </summary>
        internal static string HomeXPathJapanese {
            get {
                return ResourceManager.GetString("HomeXPathJapanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;pl&apos;]/a.
        /// </summary>
        internal static string HomeXPathPolish {
            get {
                return ResourceManager.GetString("HomeXPathPolish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;pt&apos;]/a.
        /// </summary>
        internal static string HomeXPathPortuguese {
            get {
                return ResourceManager.GetString("HomeXPathPortuguese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;ru&apos;]/a.
        /// </summary>
        internal static string HomeXPathRussian {
            get {
                return ResourceManager.GetString("HomeXPathRussian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //div[@lang=&apos;es&apos;]/a.
        /// </summary>
        internal static string HomeXPathSpanish {
            get {
                return ResourceManager.GetString("HomeXPathSpanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
    }
}
